# Generated by Django 3.2.11 on 2022-06-04 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito_Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('cod_producto', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Carrito_Compras',
                'verbose_name_plural': 'Carrito_Compras',
                'db_table': 'Carrito_Compras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comuna', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'db_table': 'Comuna',
                'ordering': ['nombre_comuna'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'db_table': 'contacto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Detalle_Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('stock_inicial', models.IntegerField()),
                ('stock_actual', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Detalle_Ingreso',
                'verbose_name_plural': 'Detalle_Ingresos',
                'db_table': 'Detalle_Ingreso',
                'ordering': ['precio_compra'],
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.ImageField(null=True, upload_to='marcas')),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'db_table': 'marcas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Metodo_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_metodo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Nombre',
                'verbose_name_plural': 'Nombres',
                'db_table': 'Metodo_Pago',
                'ordering': ['nombre_metodo'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_region', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regiones',
                'db_table': 'Region',
                'ordering': ['nombre_region'],
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['id'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Cliente'},
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='Cliente',
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('email_venta', models.CharField(max_length=50)),
                ('fecha_venta', models.DateField()),
                ('estado_venta', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monto',
                'verbose_name_plural': 'Montos',
                'db_table': 'Venta',
                'ordering': ['monto'],
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('usuario', models.CharField(max_length=20)),
                ('password', models.BinaryField()),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.venta')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'db_table': 'Trabajador',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_provincia', models.CharField(max_length=50)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.region')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'Provincia',
                'ordering': ['nombre_provincia'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('razon_social', models.CharField(max_length=150)),
                ('sector_comercial', models.CharField(max_length=50)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('num_documento', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.comuna')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedor',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('descripcion', models.CharField(max_length=500)),
                ('precio', models.PositiveIntegerField()),
                ('stock', models.IntegerField(default=0, null=True)),
                ('oferta', models.BooleanField(default=False)),
                ('videoid', models.CharField(max_length=100, null=True)),
                ('destacado', models.BooleanField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.categorias')),
                ('detalle_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.detalle_ingreso')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.marcas')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_comprobante', models.CharField(max_length=50)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.proveedor')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'db_table': 'Ingreso',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna_envio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.comuna')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'db_table': 'Envio',
                'ordering': ['comuna_envio'],
            },
        ),
        migrations.AddField(
            model_name='detalle_ingreso',
            name='ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.ingreso'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.provincia'),
        ),
    ]
