# Generated by Django 3.2.11 on 2022-06-04 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_cliente_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='comuna_envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.region'),
        ),
    ]
