# Generated by Django 3.2.11 on 2022-06-04 04:20

import argparse
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cliente_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='comuna',
            field=models.ForeignKey(on_delete=argparse.Action, to='app.comuna'),
        ),
    ]
