# Generated by Django 3.2.11 on 2022-06-04 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220604_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.provincia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.region'),
            preserve_default=False,
        ),
    ]
