# Generated by Django 3.2.11 on 2022-06-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20220604_0054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['id'], 'verbose_name': 'CLIENTE', 'verbose_name_plural': 'CLIENTES'},
        ),
        migrations.AlterModelOptions(
            name='comuna',
            options={'ordering': ['id'], 'verbose_name': 'COMUNA', 'verbose_name_plural': 'COMUNAS'},
        ),
        migrations.AlterModelOptions(
            name='envio',
            options={'ordering': ['id'], 'verbose_name': 'ENVIO', 'verbose_name_plural': 'ENVIOS'},
        ),
        migrations.AlterModelOptions(
            name='metodo_pago',
            options={'ordering': ['id'], 'verbose_name': 'METODO_PAGO', 'verbose_name_plural': 'METODO_PAGOS'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'ordering': ['id'], 'verbose_name': 'PROVINCIA', 'verbose_name_plural': 'PROVINCIA'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['id'], 'verbose_name': 'REGION', 'verbose_name_plural': 'REGIONES'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='test',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='detalle_ingreso',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='oferta',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='categorias',
            table='categoria',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='CLIENTE',
        ),
        migrations.AlterModelTable(
            name='comuna',
            table='COMUNA',
        ),
        migrations.AlterModelTable(
            name='envio',
            table='ENVIO',
        ),
        migrations.AlterModelTable(
            name='marcas',
            table='marca',
        ),
        migrations.AlterModelTable(
            name='metodo_pago',
            table='METODO_PAGO',
        ),
        migrations.AlterModelTable(
            name='provincia',
            table='PROVINCIA',
        ),
        migrations.AlterModelTable(
            name='region',
            table='REGION',
        ),
    ]
