# Generated by Django 3.2.11 on 2022-06-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20220604_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Blocke_y_num',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
