# Generated by Django 3.2.11 on 2022-06-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20220604_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Blocke_y_num',
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
    ]
