# Generated by Django 3.2.11 on 2022-06-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_cliente_blocke_y_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ape_materno',
            field=models.CharField(default=1, max_length=50, verbose_name='Apellido materno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Primer nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre de usuario'),
        ),
    ]
