# Generated by Django 3.2.11 on 2022-06-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20220604_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Blocke_y_num',
        ),
        migrations.AddField(
            model_name='cliente',
            name='calle',
            field=models.CharField(default=1, max_length=50, verbose_name='Calle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='depto',
            field=models.CharField(default=1, max_length=100, verbose_name='N° depto / oficina / otro dato (si aplica)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.IntegerField(default=1, max_length=5, verbose_name='Número'),
            preserve_default=False,
        ),
    ]
