# Generated by Django 3.2.11 on 2022-06-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20220604_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='depto',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° depto / oficina / otro dato (si aplica)'),
        ),
    ]
