# Generated by Django 3.2.11 on 2022-06-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20220604_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.IntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='detalle_ingreso',
            name='precio_compra',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detalle_ingreso',
            name='precio_venta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detalle_ingreso',
            name='stock_actual',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detalle_ingreso',
            name='stock_inicial',
            field=models.IntegerField(),
        ),
    ]
