# Generated by Django 3.2.11 on 2022-06-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20220604_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.IntegerField(default=0, verbose_name='Número'),
        ),
    ]
