# Generated by Django 3.2.11 on 2022-06-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_cliente_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcas',
            name='marca',
            field=models.ImageField(default=1, upload_to='marcas'),
            preserve_default=False,
        ),
    ]
