# Generated by Django 3.2.11 on 2022-06-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_marcas_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcas',
            name='marca',
            field=models.ImageField(null=True, upload_to='marcas'),
        ),
    ]
