# Generated by Django 3.2.11 on 2022-06-05 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_marcas_marca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marcas',
            old_name='marca',
            new_name='imagen',
        ),
    ]
