# Generated by Django 3.2.13 on 2022-06-06 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_rename_marca_marcas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito_compras',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='carrito_compras',
            name='cod_producto',
            field=models.IntegerField(verbose_name='Codigo del producto'),
        ),
        migrations.AlterField(
            model_name='carrito_compras',
            name='subtotal',
            field=models.IntegerField(verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(max_length=50, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='nombre_comuna',
            field=models.CharField(max_length=50, verbose_name='Nombre comuna'),
        ),
        migrations.AlterField(
            model_name='detalle_ingreso',
            name='precio_compra',
            field=models.IntegerField(verbose_name='Precio de compra'),
        ),
        migrations.AlterField(
            model_name='detalle_ingreso',
            name='precio_venta',
            field=models.IntegerField(verbose_name='Precio de venta'),
        ),
        migrations.AlterField(
            model_name='detalle_ingreso',
            name='stock_actual',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Stock actual'),
        ),
        migrations.AlterField(
            model_name='detalle_ingreso',
            name='stock_inicial',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Stock inicial'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='tipo_comprobante',
            field=models.CharField(max_length=50, verbose_name='Tipo de comprobante'),
        ),
        migrations.AlterField(
            model_name='marcas',
            name='imagen',
            field=models.ImageField(null=True, upload_to='marcas', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='marcas',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='metodo_pago',
            name='nombre_metodo',
            field=models.CharField(max_length=50, verbose_name='Metodo de pago'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(max_length=500, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='destacado',
            field=models.BooleanField(verbose_name='¿Es destacado?'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.PositiveIntegerField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='videoid',
            field=models.CharField(max_length=100, null=True, verbose_name='Enlace del video'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='num_documento',
            field=models.IntegerField(verbose_name='Numero de documento'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(max_length=150, verbose_name='Razon social'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='sector_comercial',
            field=models.CharField(max_length=50, verbose_name='Sector comercial'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.IntegerField(verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_documento',
            field=models.CharField(max_length=50, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='url',
            field=models.CharField(max_length=100, verbose_name='Enlace sitio web'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre_provincia',
            field=models.CharField(max_length=50, verbose_name='Nombre provincia'),
        ),
        migrations.AlterField(
            model_name='region',
            name='abreviatura',
            field=models.CharField(max_length=4, verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='region',
            name='capital',
            field=models.CharField(max_length=64, verbose_name='Capital'),
        ),
        migrations.AlterField(
            model_name='region',
            name='nombre_region',
            field=models.CharField(max_length=50, verbose_name='Nombre region'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='apellido_materno',
            field=models.CharField(max_length=30, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='apellido_paterno',
            field=models.CharField(max_length=30, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='password',
            field=models.BinaryField(verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='telefono',
            field=models.IntegerField(verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='usuario',
            field=models.CharField(max_length=20, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado_venta',
            field=models.CharField(max_length=50, verbose_name='Estado de la venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(verbose_name='Fecha de la venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='monto',
            field=models.IntegerField(verbose_name='Monto'),
        ),
    ]
