# Generated by Django 3.2.13 on 2022-06-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_marcas_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecificacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Especificacion',
                'verbose_name_plural': 'Especificaciones',
            },
        ),
        migrations.CreateModel(
            name='EspecificacionProductoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=50, verbose_name='Detalle')),
                ('especificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.especificacionproducto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.productos')),
            ],
            options={
                'verbose_name': 'Detalle Especificacion',
                'verbose_name_plural': 'Detalles Especificaciones',
            },
        ),
    ]
