# Generated by Django 3.2.11 on 2022-06-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_marcas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='url',
            field=models.URLField(verbose_name='Enlace sitio web'),
        ),
    ]
