# Generated by Django 3.2.13 on 2022-06-17 05:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20220615_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='descuento',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Descuento'),
        ),
    ]
