# Generated by Django 3.2.13 on 2022-06-17 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20220617_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descuento',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Precio'),
        ),
    ]
